{
 "title": "Spring Rest",
 "tags": [
  "Spring Boot",
  "spring"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "application",
    "label": "Application",
    "query": "SHOW TAG VALUES   FROM \"jvm_memory_used\" WITH KEY = \"application\""
   },
   {
    "name": "host",
    "label": "Host",
    "query": "SHOW TAG VALUES FROM jvm_memory_used WITH KEY = \"host\" WHERE  \"application\" =~ /^$application$/ AND time > now() - 1m "
   },
   { "name": "instance", "label": "Instance", "query": " host:port" },
   {
    "name": "env",
    "label": "env",
    "query": "SHOW TAG VALUES   FROM \"jvm_memory_used\" WITH KEY = \"env\""
   },
   {
    "name": "Interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "cores",
    "label": "cores",
    "query": "SELECT max(\"value\") FROM system_cpu_count WHERE \"application\" =~ /^$application$/ AND \"host\" =~ /^$host$/ AND time > now() - 1m "
   },
   {
    "name": "endpoint",
    "label": "endpoint",
    "query": "SHOW TAG VALUES   FROM \"http_server_requests\" WITH KEY = \"uri\" WHERE \"application\" =~ /^$application$/"
   },
   { "name": "report_interval", "label": "report Interval", "query": "10s" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Applications QPS",
   "type": "graph",
   "description": "Applications QPS(HTTP Requests) ",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Requests / seconds" }
   ],
   "targets": [
    {
     "alias": "$tag_application",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "application" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_server_requests",
     "query": "SELECT sum(\"count\")  / 60 FROM \"http_server_requests\" WHERE $timeFilter GROUP BY time(1m), \"application\" fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 60" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Application RT",
   "type": "graph",
   "description": "Application  Requests Timed and Slowest Top 10  Duration",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_application",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "application" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "http_server_requests",
     "query": "SELECT sum(\"sum\") FROM \"http_server_requests\" WHERE $timeFilter GROUP BY time($__interval), \"application\" fill(0)",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Application Errors Rate(Errors / Minute)",
   "type": "graph",
   "description": "每分钟应用、实例调用的异常次数",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "alias": "$tag_application",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "application" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_server_requests",
     "query": "SELECT sum(\"count\") FROM \"http_server_requests\" WHERE (\"exception\" != 'None') AND $timeFilter GROUP BY time($__interval), \"application\" fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "exception", "operator": "!=", "value": "None" }
     ]
    }
   ]
  },
  {
   "title": "Application Requests Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "alias": "$tag_application",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "application" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "http_server_requests",
     "query": "SELECT sum(\"count\")  / 10 FROM \"http_server_requests\" WHERE $timeFilter GROUP BY time(10s) fill(none)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Application Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "QPS Requests",
   "type": "graph",
   "description": "QPS(HTTP Requests)  and Top 10 QPS ",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short", "label": "Requests / seconds" }
   ],
   "targets": [
    {
     "alias": "ALL QPS",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_server_requests",
     "query": "SELECT sum(\"count\")  / 10 FROM \"http_server_requests\" WHERE $timeFilter GROUP BY time(10s) fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 60" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "$tag_uri",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "uri" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "http_server_requests",
     "query": "SELECT sum(\"count\")  / 10 FROM \"http_server_requests\" WHERE $timeFilter GROUP BY time(10s), \"uri\" fill(none)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 60" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "All Requests Timed",
   "type": "graph",
   "description": "All HTTP Requests Timed and Slowest Top 10  Duration",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_uri",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "uri" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "http_server_requests",
     "query": "SELECT sum(\"sum\")  / sum(\"count\") FROM \"http_server_requests\" WHERE $timeFilter GROUP BY time(10m), \"uri\" fill(0)",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [
         " / sum(\"count\")"
        ],
        "type": "math"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Requests Count",
   "type": "graph",
   "description": "HTTP Requests Count  and Top 10 Requests",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "locale", "label": "Requests / min" }
   ],
   "targets": [
    {
     "alias": "TOTAL",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_server_requests",
     "query": "SELECT sum(\"count\") FROM \"http_server_requests\" WHERE (\"application\" =~ /^$application$/ AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "$tag_uri",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "uri" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_server_requests",
     "query": "SELECT sum(\"count\") FROM \"http_server_requests\" WHERE (\"application\" =~ /^$application$/ AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval), \"uri\" fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "TP90 Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "TP90",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "http_server_requests",
     "query": "SELECT mean(\"90_percentile\") FROM \"http_server_requests\" WHERE $timeFilter GROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "90_percentile" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "$tag_uri",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "uri" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "http_server_requests",
     "query": "SELECT percentile(\"mean\", 90) FROM \"http_server_requests\" WHERE $timeFilter GROUP BY time(1m) fill(0)",
     "select": [
      [
       { "params": [ "90_percentile" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "TP Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "TP999",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "http_server_requests",
     "query": "SELECT percentile(\"mean\", 99.9) FROM \"http_server_requests\" WHERE $timeFilter GROUP BY time(1m) fill(0)",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       { "params": [ "99.9" ], "type": "percentile" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" }
     ]
    },
    {
     "alias": "TP99",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "http_server_requests",
     "query": "SELECT percentile(\"mean\", 99.9) FROM \"http_server_requests\" WHERE $timeFilter GROUP BY time(1m) fill(0)",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       { "params": [ "99" ], "type": "percentile" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" }
     ]
    },
    {
     "alias": "TP95",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "http_server_requests",
     "query": "SELECT percentile(\"mean\", 99.9) FROM \"http_server_requests\" WHERE $timeFilter GROUP BY time(1m) fill(0)",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       { "params": [ "95" ], "type": "percentile" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" }
     ]
    },
    {
     "alias": "TP90",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "http_server_requests",
     "query": "SELECT percentile(\"mean\", 99.9) FROM \"http_server_requests\" WHERE $timeFilter GROUP BY time(1m) fill(0)",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       { "params": [ "90" ], "type": "percentile" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" }
     ]
    },
    {
     "alias": "TP80",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "http_server_requests",
     "query": "SELECT percentile(\"mean\", 99.9) FROM \"http_server_requests\" WHERE $timeFilter GROUP BY time(1m) fill(0)",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       { "params": [ "80" ], "type": "percentile" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" }
     ]
    },
    {
     "alias": "TP50",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "http_server_requests",
     "query": "SELECT percentile(\"mean\", 50) FROM \"http_server_requests\" WHERE (\"uri\" = '/v1/user/home') AND $timeFilter GROUP BY time(1m) fill(0)",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       { "params": [ "50" ], "type": "percentile" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" }
     ]
    },
    {
     "alias": "TP_90_mm",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "http_server_requests",
     "query": "SELECT \"90_percentile\" FROM \"http_server_requests\" WHERE $timeFilter GROUP BY time(1m) fill(0)",
     "select": [
      [
       { "params": [ "90_percentile" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "All Requests Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "alias": "TOTAL",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "http_server_requests",
     "query": "SELECT sum(\"count\")  / 10 FROM \"http_server_requests\" WHERE $timeFilter GROUP BY time(10s) fill(none)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "ERROR",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "http_server_requests",
     "query": "SELECT sum(\"count\")  / 10 FROM \"http_server_requests\" WHERE $timeFilter GROUP BY time(10s) fill(none)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "exception", "operator": "!=", "value": "None" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Request Errors Rate(Errors / Requests Per Minute)",
   "type": "graph",
   "description": "(应用、实例调用的异常调用异常次数）/请求数",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "percentunit", "label": " Errors / Requests" }
   ],
   "targets": [
    {
     "alias": "TOTAL",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "http_server_requests",
     "query": "SELECT sum(\"count\")  / 10 FROM \"http_server_requests\" WHERE $timeFilter GROUP BY time(10s) fill(none)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "ERROR",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "http_server_requests",
     "query": "SELECT sum(\"count\")  / 10 FROM \"http_server_requests\" WHERE $timeFilter GROUP BY time(10s) fill(none)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "exception", "operator": "!=", "value": "None" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Request Errors Rate(Errors / Minute)",
   "type": "graph",
   "description": "每分钟应用、实例调用的异常次数",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 78 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "alias": "Error Requests",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_server_requests",
     "query": "SELECT sum(\"count\") FROM \"http_server_requests\" WHERE (\"uri\" = '/') AND $timeFilter GROUP BY time($__interval), \"status\" fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "exception", "operator": "!=", "value": "None" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Requests Interface Errors",
   "type": "graph",
   "description": "HTTP Requests Interface Errors  and TOP 10 Failed Request",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "alias": "$tag_uri",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "uri" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "http_server_requests",
     "query": "SELECT sum(\"count\") FROM \"http_server_requests\" WHERE (\"exception\" != 'None') AND $timeFilter GROUP BY time($__interval), \"uri\" fill(none)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "exception", "operator": "!=", "value": "None" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Requests Interface Errors",
   "type": "graph",
   "description": "interface errors",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 95 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "alias": "$tag_uri",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "uri" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "http_server_requests",
     "query": "SELECT sum(\"count\") FROM \"http_server_requests\" WHERE (\"uri\" = '/') AND $timeFilter GROUP BY time($__interval), \"status\" fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "exception", "operator": "!=", "value": "None" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Requests Exception",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 95 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "alias": "$tag_exception",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "exception" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_server_requests",
     "query": "SELECT sum(\"count\") FROM \"http_server_requests\" WHERE (\"uri\" = '/') AND $timeFilter GROUP BY time($__interval), \"status\" fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "exception", "operator": "!=", "value": "None" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Daily Requests Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 104 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "alias": "Request Count",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "http_server_requests",
     "query": "SELECT sum(\"count\")  / 10 FROM \"http_server_requests\" WHERE $timeFilter GROUP BY time(10s) fill(none)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Requests Status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 113 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_status",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "status" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_server_requests",
     "query": "SELECT sum(\"count\") FROM \"http_server_requests\" WHERE (\"uri\" = '/') AND $timeFilter GROUP BY time($__interval), \"status\" fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Requests Outcome",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 113 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_outcome",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "outcome" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_server_requests",
     "query": "SELECT sum(\"count\") FROM \"http_server_requests\" WHERE (\"uri\" = '/') AND $timeFilter GROUP BY time($__interval), \"status\" fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Count(HTTP Requests)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 121 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "alias": "$tag_uri",
     "groupBy": [
      { "params": [ "uri" ], "type": "tag" }
     ],
     "measurement": "http_server_requests",
     "query": "SELECT sum(\"count\")    FROM \"http_server_requests\" WHERE $timeFilter GROUP BY  time(1m), \"uri\" fill(0) ",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Log Events",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 129 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_level",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "level" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "logback_events",
     "query": "SELECT sum(\"value\") FROM \"logback_events\" WHERE (\"application\" =~ /^$application$/ AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval), \"level\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  }
 ]
}