{
 "title": "Spring Boot",
 "tags": [
  "Spring Boot",
  "spring"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "application",
    "label": "Application",
    "query": "SHOW TAG VALUES   FROM \"jvm_memory_used\" WITH KEY = \"application\""
   },
   {
    "name": "host",
    "label": "Host",
    "query": "SHOW TAG VALUES FROM jvm_memory_used WITH KEY = \"host\" WHERE \"application\" =~ /^$application$/  AND time > now()-10m "
   },
   { "name": "instance", "label": "Instance", "query": "host:9090" },
   {
    "name": "env",
    "label": "env",
    "query": "SHOW TAG VALUES   FROM \"jvm_memory_used\" WITH KEY = \"env\""
   },
   {
    "name": "Interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "executor_name",
    "label": "executor_name",
    "query": "SHOW TAG VALUES FROM \"executor_active\" WITH KEY = \"name\" WHERE \"application\" =~ /^$application$/ and  \"host\"=~ /^$host$/"
   },
   {
    "name": "cores",
    "label": "cores",
    "query": "SELECT max(\"value\") FROM \"system_cpu_count\" WHERE \"application\" =~ /^$application$/ AND \"host\" =~ /^$host$/ AND time > now() - 1m "
   },
   { "name": "report_interval", "label": "report Interval", "query": "10s" }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP Requests",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_status",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "status" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "http_server_requests",
       "query": "SELECT sum(\"count\") FROM \"http_server_requests\" WHERE (\"uri\" = '/') AND $timeFilter GROUP BY time($__interval), \"status\" fill(null)",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Log Events",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_level",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "level" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "logback_events",
       "query": "SELECT sum(\"value\") FROM \"logback_events\" WHERE (\"application\" =~ /^$application$/ AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval), \"level\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "alias": "System CPU Usage",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "system_cpu_usage",
       "query": "SELECT mean(\"value\") FROM \"system_cpu_usage\" WHERE (\"application\" =~ /^$application$/ AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "Process CPU Usage",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "process_cpu_usage",
       "query": "SELECT mean(\"value\") FROM \"process_cpu_usage\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Load Average",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Load Average[1m]",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "system_load_average_1m",
       "query": "SELECT mean(\"value\") FROM \"system_load_average_1m\" WHERE (\"application\" =~ /^$application$/ AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "CPU Cores",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "system_cpu_count",
       "query": "SELECT mean(\"value\") FROM \"system_cpu_usage\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Memory Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Heap memory",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "used",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jvm_memory_used",
       "query": "SELECT sum(\"value\") FROM \"jvm_memory_used\" WHERE (\"area\" = 'heap' AND \"application\" =~ /^$application$/ AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "area", "operator": "=", "value": "heap" },
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "committed",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jvm_memory_committed",
       "query": "SELECT sum(\"value\") FROM \"jvm_memory_committed\" WHERE (\"area\" = 'heap') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "area", "operator": "=", "value": "heap" },
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "max",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jvm_memory_max",
       "query": "SELECT sum(\"value\") FROM \"jvm_memory_max\" WHERE (\"area\" = 'heap') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "area", "operator": "=", "value": "heap" },
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Non-heap memory",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "used",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jvm_memory_used",
       "query": "SELECT sum(\"value\") FROM \"jvm_memory_used\" WHERE (\"area\" = 'nonheap') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "area", "operator": "=", "value": "nonheap" },
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "committed",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jvm_memory_committed",
       "query": "SELECT sum(\"value\") FROM \"jvm_memory_committed\" WHERE (\"area\" = 'nonheap') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "area", "operator": "=", "value": "nonheap" },
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "max",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jvm_memory_max",
       "query": "SELECT sum(\"value\") FROM \"jvm_memory_committed\" WHERE (\"area\" = 'nonheap') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "area", "operator": "=", "value": "nonheap" },
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Heap memory used",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "$tag_id",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "id" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jvm_memory_used",
       "query": "SELECT mean(\"value\") FROM \"jvm_memory_used\" WHERE (\"area\" = 'nonheap') AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "area", "operator": "=", "value": "heap" },
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Non-heap memory used",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "$tag_id",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "id" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jvm_memory_used",
       "query": "SELECT mean(\"value\") FROM \"jvm_memory_used\" WHERE (\"area\" = 'nonheap') AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "area", "operator": "=", "value": "nonheap" },
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Memory Pools (Heap)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "PS Eden Space",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "used",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jvm_memory_used",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "area", "operator": "=", "value": "heap" },
        { "condition": "AND", "key": "id", "operator": "=", "value": "Par_Eden_Space" },
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "committed",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jvm_memory_committed",
       "query": "SELECT mean(\"value\") FROM \"jvm_memory_max\" WHERE (\"area\" = 'heap') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "area", "operator": "=", "value": "heap" },
        { "condition": "AND", "key": "id", "operator": "=", "value": "Par_Eden_Space" },
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "max",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jvm_memory_max",
       "query": "SELECT mean(\"value\") FROM \"jvm_memory_max\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "area", "operator": "=", "value": "heap" },
        { "condition": "AND", "key": "id", "operator": "=", "value": "Par_Eden_Space" },
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "PS Survivor Space",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 3 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "used",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jvm_memory_used",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "area", "operator": "=", "value": "heap" },
        { "condition": "AND", "key": "id", "operator": "=", "value": "Par_Survivor_Space" },
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "committed",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jvm_memory_committed",
       "query": "SELECT mean(\"value\") FROM \"jvm_memory_max\" WHERE (\"area\" = 'heap') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "area", "operator": "=", "value": "heap" },
        { "condition": "AND", "key": "id", "operator": "=", "value": "Par_Survivor_Space" },
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "max",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jvm_memory_max",
       "query": "SELECT mean(\"value\") FROM \"jvm_memory_max\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "area", "operator": "=", "value": "heap" },
        { "condition": "AND", "key": "id", "operator": "=", "value": "Par_Survivor_Space" },
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "PS Old Gen",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 3 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "used",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jvm_memory_used",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "area", "operator": "=", "value": "heap" },
        { "condition": "AND", "key": "id", "operator": "=", "value": "CMS_Old_Gen" },
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "committed",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jvm_memory_committed",
       "query": "SELECT mean(\"value\") FROM \"jvm_memory_max\" WHERE (\"area\" = 'heap') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "area", "operator": "=", "value": "heap" },
        { "condition": "AND", "key": "id", "operator": "=", "value": "CMS_Old_Gen" },
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "max",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jvm_memory_max",
       "query": "SELECT mean(\"value\") FROM \"jvm_memory_max\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "area", "operator": "=", "value": "heap" },
        { "condition": "AND", "key": "id", "operator": "=", "value": "CMS_Old_Gen" },
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Memory Pools (Non-Heap)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Metaspace",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "used",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "id" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jvm_memory_used",
       "query": "SELECT mean(\"value\") FROM \"jvm_memory_used\" WHERE (\"area\" = 'nonheap') AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "area", "operator": "=", "value": "nonheap" },
        { "condition": "AND", "key": "id", "operator": "=", "value": "Metaspace" },
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "committed",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jvm_memory_committed",
       "query": "SELECT mean(\"value\") FROM \"jvm_memory_max\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "area", "operator": "=", "value": "nonheap" },
        { "condition": "AND", "key": "id", "operator": "=", "value": "Metaspace" },
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "max",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jvm_memory_max",
       "query": "SELECT mean(\"value\") FROM \"jvm_memory_max\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "area", "operator": "=", "value": "nonheap" },
        { "condition": "AND", "key": "id", "operator": "=", "value": "Metaspace" },
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Compressed Class Space",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 34 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "used",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "id" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jvm_memory_used",
       "query": "SELECT mean(\"value\") FROM \"jvm_memory_used\" WHERE (\"area\" = 'nonheap') AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "area", "operator": "=", "value": "nonheap" },
        { "condition": "AND", "key": "id", "operator": "=", "value": "Compressed_Class_Space" },
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "committed",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jvm_memory_committed",
       "query": "SELECT mean(\"value\") FROM \"jvm_memory_max\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "area", "operator": "=", "value": "nonheap" },
        { "condition": "AND", "key": "id", "operator": "=", "value": "Compressed_Class_Space" },
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "max",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jvm_memory_max",
       "query": "SELECT mean(\"value\") FROM \"jvm_memory_max\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "area", "operator": "=", "value": "nonheap" },
        { "condition": "AND", "key": "id", "operator": "=", "value": "Compressed_Class_Space" },
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Code Cache",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 34 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "used",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "id" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jvm_memory_used",
       "query": "SELECT mean(\"value\") FROM \"jvm_memory_used\" WHERE (\"area\" = 'nonheap') AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "area", "operator": "=", "value": "nonheap" },
        { "condition": "AND", "key": "id", "operator": "=", "value": "Code_Cache" },
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "committed",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jvm_memory_committed",
       "query": "SELECT mean(\"value\") FROM \"jvm_memory_max\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "area", "operator": "=", "value": "nonheap" },
        { "condition": "AND", "key": "id", "operator": "=", "value": "Code_Cache" },
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "max",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jvm_memory_max",
       "query": "SELECT mean(\"value\") FROM \"jvm_memory_max\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "area", "operator": "=", "value": "nonheap" },
        { "condition": "AND", "key": "id", "operator": "=", "value": "Code_Cache" },
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Threads",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Daemon",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jvm_threads_daemon",
       "query": "SELECT mean(\"value\") FROM \"process_cpu_usage\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "Live",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jvm_threads_live",
       "query": "SELECT mean(\"value\") FROM \"system_load_average_1m\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "Peak",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jvm_threads_peak",
       "query": "SELECT mean(\"value\") FROM \"system_load_average_1m\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Threads",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_state",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "state" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jvm_threads_states",
       "query": "SELECT mean(\"value\") FROM \"process_cpu_usage\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Classes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Loaded",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jvm_classes_loaded",
       "query": "SELECT mean(\"value\") FROM \"jvm_classes_loaded\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "Unloaded",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jvm_classes_unloaded",
       "query": "SELECT mean(\"value\") FROM \"jvm_classes_unloaded\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "File Descriptors ",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "open",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "process_files_open",
       "query": "SELECT mean(\"value\") FROM \"process_files_max\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "max",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "process_files_max",
       "query": "SELECT mean(\"value\") FROM \"process_cpu_usage\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 60 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "Uptime",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "process_uptime",
       "query": "SELECT last(\"value\") FROM \"process_uptime\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Garbage Collection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC Live",
     "type": "graph",
     "description": "live ： Size of old generation memory pool after a full GC\nmax: Size of old generation memory pool after a full GC",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "live",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jvm_gc_live_data_size",
       "query": "SELECT mean(\"value\") FROM \"jvm_classes_loaded\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "max",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jvm_gc_max_data_size",
       "query": "SELECT mean(\"value\") FROM \"jvm_classes_unloaded\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "GC Allocated/Promoted",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "allocated",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jvm_gc_memory_allocated",
       "query": "SELECT mean(\"value\") FROM \"jvm_classes_loaded\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "promoted",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jvm_gc_memory_promoted",
       "query": "SELECT mean(\"value\") FROM \"jvm_classes_unloaded\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "GC Pause",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jvm_gc_pause",
       "query": "SELECT max(\"value\") FROM \"jvm_gc_pause\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Buffer Pools",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Direct Buffers",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "used",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jvm_buffer_memory_used",
       "query": "SELECT mean(\"value\") FROM \"jvm_memory_used\" WHERE (\"area\" = 'nonheap') AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "id", "operator": "=", "value": "direct" },
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "capacity",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jvm_buffer_total_capacity",
       "query": "SELECT mean(\"value\") FROM \"jvm_memory_max\" WHERE (\"area\" = 'nonheap') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "id", "operator": "=", "value": "direct" },
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Direct Buffers",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "count",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jvm_buffer_count",
       "query": "SELECT mean(\"value\") FROM \"jvm_memory_used\" WHERE (\"area\" = 'nonheap') AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "id", "operator": "=", "value": "direct" },
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Mapped Buffers ",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "used",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jvm_buffer_memory_used",
       "query": "SELECT mean(\"value\") FROM \"jvm_memory_used\" WHERE (\"area\" = 'nonheap') AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "id", "operator": "=", "value": "mapped" },
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "capacity",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jvm_buffer_total_capacity",
       "query": "SELECT mean(\"value\") FROM \"jvm_memory_max\" WHERE (\"area\" = 'nonheap') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "id", "operator": "=", "value": "mapped" },
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Mapped Buffers ",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "count",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jvm_buffer_count",
       "query": "SELECT mean(\"value\") FROM \"jvm_memory_used\" WHERE (\"area\" = 'nonheap') AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "id", "operator": "=", "value": "mapped" },
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "JDBC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "dataSource",
     "type": "graph",
     "description": "The current number of active connections.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "active",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "dataSource_connections_active",
       "query": "SELECT mean(\"value\") FROM \"kafka_consumer_fetch_total\" WHERE (\"application\" =~ /^$application$/ AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "min",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "dataSource_connections_min",
       "query": "SELECT mean(\"value\") FROM \"kafka_consumer_fetch_total\" WHERE (\"application\" =~ /^$application$/ AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "max",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "dataSource_connections_max",
       "query": "SELECT mean(\"value\") FROM \"kafka_consumer_fetch_total\" WHERE (\"application\" =~ /^$application$/ AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "ThreadPool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "ThreadPool",
     "type": "graph",
     "description": "The current number of active ThreadPoolExecutor.",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "alias": "active",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "executor_active",
       "query": "SELECT mean(\"value\") FROM \"kafka_consumer_fetch_total\" WHERE (\"application\" =~ /^$application$/ AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$executor_name$/" }
       ]
      },
      {
       "alias": "size",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "executor_pool_size",
       "query": "SELECT mean(\"value\") FROM \"kafka_consumer_fetch_total\" WHERE (\"application\" =~ /^$application$/ AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$executor_name$/" }
       ]
      },
      {
       "alias": "core",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "executor_pool_core",
       "query": "SELECT mean(\"value\") FROM \"kafka_consumer_fetch_total\" WHERE (\"application\" =~ /^$application$/ AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$executor_name$/" }
       ]
      },
      {
       "alias": "max",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "executor_pool_max",
       "query": "SELECT mean(\"value\") FROM \"kafka_consumer_fetch_total\" WHERE (\"application\" =~ /^$application$/ AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$executor_name$/" }
       ]
      }
     ]
    },
    {
     "title": "ThreadPool Queue",
     "type": "graph",
     "description": "The current number of active ThreadPoolExecutor Queue",
     "gridPos": { "h": 9, "w": 13, "x": 11, "y": 37 },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "alias": "used",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "executor_queued",
       "query": "SELECT mean(\"value\") FROM \"kafka_consumer_fetch_total\" WHERE (\"application\" =~ /^$application$/ AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$executor_name$/" }
       ]
      },
      {
       "alias": "remaining",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "executor_queue_remaining",
       "query": "SELECT mean(\"value\") FROM \"kafka_consumer_fetch_total\" WHERE (\"application\" =~ /^$application$/ AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$executor_name$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Netty",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "connections",
     "type": "graph",
     "description": "The current number of active connections.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "active",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "netty_connections_active",
       "query": "SELECT mean(\"value\") FROM \"kafka_consumer_fetch_total\" WHERE (\"application\" =~ /^$application$/ AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "registered",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "netty_connections_registered",
       "query": "SELECT mean(\"value\") FROM \"kafka_consumer_fetch_total\" WHERE (\"application\" =~ /^$application$/ AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}